name: Build Minesweeper

on:
  push:
    branches: [ dev, master ]
    paths:
      - '**.cpp'
      - '**.h'
      - 'Makefile*'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ dev, master ]
    paths:
      - '**.cpp'
      - '**.h'
      - 'Makefile*'
      - '.github/workflows/build.yml'


  workflow_dispatch:

jobs:
  build-msdos:
    runs-on: ubuntu-latest
    container: 
      image: fedora:latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        dnf -y update
        dnf -y install wget unzip gcc-c++ make djgpp-gcc djgpp-binutils zip

    - name: Download CSDPMI
      working-directory: msdos
      run: |
        wget http://na.mirror.garr.it/mirrors/djgpp/current/v2misc/csdpmi7b.zip
        unzip -o csdpmi7b.zip -d csdpmi

    - name: Build MS-DOS Version
      working-directory: msdos
      run: |
        x86_64-pc-linux-gnu-g++ minesweeper.cpp highscores.cpp ncurses.cpp -o mnsweep.exe
        cp csdpmi/bin/CWSDPMI.EXE .

    - name: Create MS-DOS Distribution
      working-directory: msdos
      run: |
        mkdir minesweeper-msdos-v1.0
        cp mnsweep.exe minesweeper-msdos-v1.0/
        cp CWSDPMI.EXE minesweeper-msdos-v1.0/
        cp ../README.md minesweeper-msdos-v1.0/
        cp ../LICENSE.md minesweeper-msdos-v1.0/
        
        echo "Minesweeper for MS-DOS
        Version 1.0

        Installation:
        1. Ensure CWSDPMI.EXE is in the same directory as mnsweep.exe
        2. Double-click mnsweep.exe or run from command line

        Requirements:
        - MS-DOS or compatible OS
        - 4MB RAM
        - VGA or better graphics" > minesweeper-msdos-v1.0/README-MSDOS.txt
        
        zip -r ../Minesweeper-MSDOS.zip minesweeper-msdos-v1.0

    - name: Upload MS-DOS Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: msdos-artifacts
        path: |
          Minesweeper-MSDOS.zip
          msdos/mnsweep.exe
          msdos/CWSDPMI.EXE

  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
      
    - name: Setup Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build C++ Executable
      working-directory: windows
      run: |
        msbuild /p:Configuration=Release /p:Platform=x64 minesweeper.vcxproj

    - name: Install WiX Toolset
      run: |
        mkdir wix
        cd wix
        Invoke-WebRequest -Uri "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip" -OutFile "wix311-binaries.zip"
        Expand-Archive wix311-binaries.zip -DestinationPath .
        echo "$pwd" | Out-File -FilePath $env:GITHUB_PATH -Append

    - name: Create MSI Installer
      working-directory: windows
      run: |
        echo '<?xml version="1.0" encoding="UTF-8"?>
        <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
          <Product Id="*" Name="Minesweeper" Language="1033" Version="1.0.0.${{ github.run_number }}" Manufacturer="Jason Hall" UpgradeCode="A4F3B891-9D23-41DA-8E35-F94721E8F123">
            <Package InstallerVersion="200" Compressed="yes" InstallScope="perMachine" />
            <MajorUpgrade DowngradeErrorMessage="A newer version is already installed." />
            <MediaTemplate EmbedCab="yes" />
            <Directory Id="TARGETDIR" Name="SourceDir">
              <Directory Id="ProgramFilesFolder">
                <Directory Id="INSTALLFOLDER" Name="Minesweeper">
                  <Component Id="MainExecutable" Guid="67CD3A92-4F45-4E67-AC89-2A5D6F981D45">
                    <File Id="MainEXE" Name="minesweeper.exe" Source="x64/Release/minesweeper.exe" KeyPath="yes"/>
                    <File Id="IconFile" Name="icon.ico" Source="icon.ico"/>
                    <File Id="README" Name="README.md" Source="../README.md"/>
                    <File Id="LICENSE" Name="LICENSE.md" Source="../LICENSE.md"/>
                  </Component>
                </Directory>
              </Directory>
              <Directory Id="ProgramMenuFolder">
                <Directory Id="ApplicationProgramsFolder" Name="Minesweeper">
                  <Component Id="ApplicationShortcuts" Guid="B71F9E23-8A78-4B12-8C34-6789ABCD8901">
                    <Shortcut Id="ApplicationStartMenu" 
                             Name="Minesweeper" 
                             Target="[INSTALLFOLDER]minesweeper.exe" 
                             WorkingDirectory="INSTALLFOLDER"
                             Icon="MinesweeperIcon"/>
                    <RemoveFolder Id="ApplicationProgramsFolder" On="uninstall"/>
                    <RegistryValue Root="HKCU" Key="Software\Minesweeper" Name="installed" Type="integer" Value="1" KeyPath="yes"/>
                  </Component>
                </Directory>
              </Directory>
            </Directory>
            <Feature Id="ProductFeature" Title="Minesweeper" Level="1">
              <ComponentRef Id="MainExecutable" />
              <ComponentRef Id="ApplicationShortcuts" />
            </Feature>
            <Icon Id="MinesweeperIcon" SourceFile="icon.ico"/>
          </Product>
        </Wix>' > installer.wxs

        candle installer.wxs
        light installer.wixobj -out Minesweeper.msi

    - name: Upload Windows Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-artifacts
        path: |
          windows/Minesweeper.msi
          windows/x64/Release/minesweeper.exe

  build-gtk:
    runs-on: ubuntu-latest
    container: 
      image: fedora:latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        dnf -y update
        dnf -y install mingw64-gcc mingw64-gcc-c++ mingw64-gtk3 mingw64-gtkmm30 wine wine-devel wixl binutils

    - name: Build GTK Version
      working-directory: gtk
      run: |
        chmod +x compile_mingw.sh
        ./compile_mingw.sh

    - name: Create ZIP Archive
      working-directory: gtk/build
      run: |
        zip -r ../../Minesweeper-GTK.zip ./*

    - name: Create GTK MSI Installer
      working-directory: gtk
      run: |
        # Generate the DLL entries
        DLL_ENTRIES=$(cd build && for f in *.dll; do 
          if [ -f "$f" ]; then
            # Create a safe ID by removing invalid characters
            SAFE_ID=$(echo "$f" | sed 's/[^a-zA-Z0-9]/_/g')
            echo "<File Id=\"$SAFE_ID\" Name=\"$f\" Source=\"build/$f\"/>"
          fi
        done)

        # Create the WXS file with the generated DLL entries
        cat > installer-gtk.wxs << 'EOL'
        <?xml version="1.0" encoding="UTF-8"?>
        <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
          <Product Id="*" Name="Minesweeper GTK" Language="1033" Version="1.0.0.${{ github.run_number }}" Manufacturer="Jason Hall" UpgradeCode="B5F3B891-9D23-41DA-8E35-F94721E8F124">
            <Package InstallerVersion="200" Compressed="yes" InstallScope="perMachine" />
            <MajorUpgrade DowngradeErrorMessage="A newer version is already installed." />
            <MediaTemplate EmbedCab="yes" />
            <Directory Id="TARGETDIR" Name="SourceDir">
              <Directory Id="ProgramFilesFolder">
                <Directory Id="INSTALLFOLDER" Name="Minesweeper GTK">
                  <Component Id="MainExecutable" Guid="77CD3A92-4F45-4E67-AC89-2A5D6F981D46">
                    <File Id="MainEXE" Name="minesweeper_gtk.exe" Source="build/minesweeper_gtk.exe" KeyPath="yes"/>
                    <File Id="IconFile" Name="icon.ico" Source="icon.ico"/>
        EOL

        # Add the generated DLL entries
        echo "$DLL_ENTRIES" >> installer-gtk.wxs

        # Complete the WXS file
        cat >> installer-gtk.wxs << 'EOL'
                    <File Id="README" Name="README.md" Source="../README.md"/>
                    <File Id="LICENSE" Name="LICENSE.md" Source="../LICENSE.md"/>
                  </Component>
                </Directory>
              </Directory>
              <Directory Id="ProgramMenuFolder">
                <Directory Id="ApplicationProgramsFolder" Name="Minesweeper GTK">
                  <Component Id="ApplicationShortcuts" Guid="C71F9E23-8A78-4B12-8C34-6789ABCD8902">
                    <Shortcut Id="ApplicationStartMenu" 
                             Name="Minesweeper GTK" 
                             Target="[INSTALLFOLDER]minesweeper_gtk.exe" 
                             WorkingDirectory="INSTALLFOLDER"
                             Icon="MinesweeperIcon"/>
                    <RemoveFolder Id="ApplicationProgramsFolder" On="uninstall"/>
                    <RegistryValue Root="HKCU" Key="Software\MinesweeperGTK" Name="installed" Type="integer" Value="1" KeyPath="yes"/>
                  </Component>
                </Directory>
              </Directory>
            </Directory>
            <Feature Id="ProductFeature" Title="Minesweeper GTK" Level="1">
              <ComponentRef Id="MainExecutable" />
              <ComponentRef Id="ApplicationShortcuts" />
            </Feature>
            <Icon Id="MinesweeperIcon" SourceFile="icon.ico"/>
          </Product>
        </Wix>
        EOL

        # Debug output
        echo "Generated WXS file contents:"
        cat installer-gtk.wxs

        wixl -v installer-gtk.wxs -o ../Minesweeper-GTK.msi

    - name: Upload GTK Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gtk-artifacts
        path: |
          Minesweeper-GTK.msi
          Minesweeper-GTK.zip

  create-release:
    needs: [build-msdos, build-windows, build-gtk]
    runs-on: ubuntu-latest
    container: 
      image: fedora:latest
    permissions:
      contents: write
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev')
    
    steps:
    - uses: actions/checkout@v4

    - name: Install Release Tools
      run: |
        dnf -y update
        dnf -y install wget unzip

    - name: Download MS-DOS Artifacts
      uses: actions/download-artifact@v4
      with:
        name: msdos-artifacts
        path: msdos-artifacts

    - name: Download Windows Artifacts
      uses: actions/download-artifact@v4
      with:
        name: windows-artifacts
        path: windows-artifacts

    - name: Download GTK Artifacts
      uses: actions/download-artifact@v4
      with:
        name: gtk-artifacts
        path: gtk-artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          msdos-artifacts/Minesweeper-MSDOS.zip
          msdos-artifacts/mnsweep.exe
          msdos-artifacts/CWSDPMI.EXE
          windows-artifacts/Minesweeper.msi
          windows-artifacts/x64/Release/minesweeper.exe
          gtk-artifacts/Minesweeper-GTK.msi
          gtk-artifacts/Minesweeper-GTK.zip
        tag_name: ${{ github.ref == 'refs/heads/master' && format('v{0}', github.run_number) || format('bleedingedge-v{0}', github.run_number) }}
        name: ${{ github.ref == 'refs/heads/master' && format('Release {0}', github.run_number) || format('Dev Build {0}', github.run_number) }}
        draft: false
        prerelease: ${{ github.ref != 'refs/heads/master' }}
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ${{ github.ref == 'refs/heads/master' && 'Release build' || 'Development build' }}
          Commit: ${{ github.sha }}
          Build number: ${{ github.run_number }}
          
          This release includes:
          - MS-DOS version (mnsweep.exe with CWSDPMI.EXE)
          - Windows version (Minesweeper.msi)
          - GTK version (Minesweeper-GTK.msi)
          - GTK portable version (Minesweeper-GTK.zip)

    - name: Output Release URL
      if: success()
      run: |
        echo "::notice::Release available at: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref == 'refs/heads/master' && format('v{0}', github.run_number) || format('bleedingedge-v{0}', github.run_number) }}"
