name: Build Minesweeper

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
      
    - name: Setup Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build C++ Executable
      working-directory: windows
      run: |
        msbuild /p:Configuration=Release /p:Platform=x64 minesweeper.vcxproj

    - name: Install WiX Toolset
      run: |
        mkdir wix
        cd wix
        Invoke-WebRequest -Uri "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip" -OutFile "wix311-binaries.zip"
        Expand-Archive wix311-binaries.zip -DestinationPath .
        echo "$pwd" | Out-File -FilePath $env:GITHUB_PATH -Append

    - name: Create MSI Installer
      working-directory: windows
      run: |
        echo '<?xml version="1.0" encoding="UTF-8"?>
        <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
          <Product Id="*" Name="Minesweeper" Language="1033" Version="1.0.0" Manufacturer="Jason Hall" UpgradeCode="A4F3B891-9D23-41DA-8E35-F94721E8F123">
            <Package InstallerVersion="200" Compressed="yes" InstallScope="perMachine" />
            <MajorUpgrade DowngradeErrorMessage="A newer version is already installed." />
            <MediaTemplate EmbedCab="yes" />
            <Directory Id="TARGETDIR" Name="SourceDir">
              <Directory Id="ProgramFilesFolder">
                <Directory Id="INSTALLFOLDER" Name="Minesweeper">
                  <Component Id="MainExecutable" Guid="67CD3A92-4F45-4E67-AC89-2A5D6F981D45">
                    <File Id="MainEXE" Name="minesweeper.exe" Source="x64/Release/minesweeper.exe" KeyPath="yes"/>
                    <File Id="IconFile" Name="icon.ico" Source="icon.ico"/>
                    <File Id="README" Name="README.md" Source="../README.md"/>
                    <File Id="LICENSE" Name="LICENSE.md" Source="../LICENSE.md"/>
                  </Component>
                </Directory>
              </Directory>
              <Directory Id="ProgramMenuFolder">
                <Directory Id="ApplicationProgramsFolder" Name="Minesweeper">
                  <Component Id="ApplicationShortcuts" Guid="B71F9E23-8A78-4B12-8C34-6789ABCD8901">
                    <Shortcut Id="ApplicationStartMenu" 
                             Name="Minesweeper" 
                             Target="[INSTALLFOLDER]minesweeper.exe" 
                             WorkingDirectory="INSTALLFOLDER"
                             Icon="MinesweeperIcon"/>
                    <RemoveFolder Id="ApplicationProgramsFolder" On="uninstall"/>
                    <RegistryValue Root="HKCU" Key="Software\Minesweeper" Name="installed" Type="integer" Value="1" KeyPath="yes"/>
                  </Component>
                </Directory>
              </Directory>
            </Directory>
            <Feature Id="ProductFeature" Title="Minesweeper" Level="1">
              <ComponentRef Id="MainExecutable" />
              <ComponentRef Id="ApplicationShortcuts" />
            </Feature>
            <Icon Id="MinesweeperIcon" SourceFile="icon.ico"/>
          </Product>
        </Wix>' > installer.wxs

        candle installer.wxs
        light installer.wixobj -out Minesweeper.msi

    - name: Upload Windows Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-artifacts
        path: |
          windows/Minesweeper.msi
          windows/x64/Release/minesweeper.exe

  build-gtk:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64 mingw-w64-tools mingw-w64-x86-64-dev
        sudo apt-get install -y libgtk-3-dev mingw-w64-x86-64-gtk3
        sudo apt-get install -y wixl

    - name: Build GTK Version
      working-directory: gtk
      run: |
        chmod +x compile_mingw.sh
        ./compile_mingw.sh

    - name: Create ZIP Archive
      working-directory: gtk/build
      run: |
        zip -r ../../Minesweeper-GTK.zip ./*

    - name: Create GTK MSI Installer
      working-directory: gtk
      run: |
        echo '<?xml version="1.0" encoding="UTF-8"?>
        <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
          <Product Id="*" Name="Minesweeper GTK" Language="1033" Version="1.0.0" Manufacturer="Jason Hall" UpgradeCode="B5F3B891-9D23-41DA-8E35-F94721E8F124">
            <Package InstallerVersion="200" Compressed="yes" InstallScope="perMachine" />
            <MajorUpgrade DowngradeErrorMessage="A newer version is already installed." />
            <MediaTemplate EmbedCab="yes" />
            <Directory Id="TARGETDIR" Name="SourceDir">
              <Directory Id="ProgramFilesFolder">
                <Directory Id="INSTALLFOLDER" Name="Minesweeper GTK">
                  <Component Id="MainExecutable" Guid="77CD3A92-4F45-4E67-AC89-2A5D6F981D46">
                    <File Id="MainEXE" Name="minesweeper_gtk.exe" Source="build/minesweeper_gtk.exe" KeyPath="yes"/>
                    <!-- Dynamically add DLL files -->
                    <?foreach DllFile in build/*.dll ?>
                      <File Id="$(var.DllFile)" Name="$(var.DllFile)" Source="build/$(var.DllFile)"/>
                    <?endforeach?>
                    <File Id="README" Name="README.md" Source="../README.md"/>
                    <File Id="LICENSE" Name="LICENSE.md" Source="../LICENSE.md"/>
                  </Component>
                </Directory>
              </Directory>
              <Directory Id="ProgramMenuFolder">
                <Directory Id="ApplicationProgramsFolder" Name="Minesweeper GTK">
                  <Component Id="ApplicationShortcuts" Guid="C71F9E23-8A78-4B12-8C34-6789ABCD8902">
                    <Shortcut Id="ApplicationStartMenu" 
                             Name="Minesweeper GTK" 
                             Target="[INSTALLFOLDER]minesweeper_gtk.exe" 
                             WorkingDirectory="INSTALLFOLDER"/>
                    <RemoveFolder Id="ApplicationProgramsFolder" On="uninstall"/>
                    <RegistryValue Root="HKCU" Key="Software\MinesweeperGTK" Name="installed" Type="integer" Value="1" KeyPath="yes"/>
                  </Component>
                </Directory>
              </Directory>
            </Directory>
            <Feature Id="ProductFeature" Title="Minesweeper GTK" Level="1">
              <ComponentRef Id="MainExecutable" />
              <ComponentRef Id="ApplicationShortcuts" />
            </Feature>
          </Product>
        </Wix>' > installer-gtk.wxs

        wixl -v installer-gtk.wxs -o ../Minesweeper-GTK.msi

    - name: Upload GTK Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: gtk-artifacts
        path: |
          Minesweeper-GTK.msi
          Minesweeper-GTK.zip

  create-release:
    needs: [build-windows, build-gtk]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')
    permissions:
      contents: write
    
    steps:
    - name: Download Windows Artifacts
      uses: actions/download-artifact@v3
      with:
        name: windows-artifacts
        path: windows-artifacts

    - name: Download GTK Artifacts
      uses: actions/download-artifact@v3
      with:
        name: gtk-artifacts
        path: gtk-artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          windows-artifacts/Minesweeper.msi
          windows-artifacts/x64/Release/minesweeper.exe
          gtk-artifacts/Minesweeper-GTK.msi
          gtk-artifacts/Minesweeper-GTK.zip
        tag_name: ${{ github.ref == 'refs/heads/main' && format('v{0}', github.run_number) || format('bleedingedge-v{0}', github.run_number) }}
        name: ${{ github.ref == 'refs/heads/main' && format('Release {0}', github.run_number) || format('Dev Build {0}', github.run_number) }}
        draft: false
        prerelease: ${{ github.ref != 'refs/heads/main' }}
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ${{ github.ref == 'refs/heads/main' && 'Release build' || 'Development build' }}
          Commit: ${{ github.sha }}
          Build number: ${{ github.run_number }}
          
          This release includes both the standard Windows version and the GTK version:
          - Windows version (Minesweeper.msi)
          - GTK version (Minesweeper-GTK.msi)
          - GTK portable version (Minesweeper-GTK.zip)
