name: Build Sudoku

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
      
    - name: Setup Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    # Build the standalone executable
    - name: Build C++ Executable
      run: |
        msbuild /p:Configuration=Release /p:Platform=x64 minesweeper.vcxproj

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          x64/Release/minesweeper.exe
        tag_name: v${{ github.run_number }}
        name: Release ${{ github.run_number }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          Automated release from CI build
          Commit: ${{ github.sha }}
          Build number: ${{ github.run_number }}


    - name: Create Dev Build
      if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
      id: create_dev_build
      uses: softprops/action-gh-release@v1
      with:
        files: |
          x64/Release/minesweeper.exe
        tag_name: bleedingedge-v${{ github.run_number }}
        name: Dev Build ${{ github.run_number }}
        draft: false
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          Development build
          Commit: ${{ github.sha }}
          Build number: ${{ github.run_number }}
